name: Build and Deploy Vue Application to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
        with:
          username: 'ghost-tremble'
          reponame: 'cw3-pwa'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'  # Specify the branch you want to deploy to
